version: "2"

services:

  lb:
    extends:
      file: common-services.yml
      service: lb
    links:
      - zendserver

  lb-ui:
    extends:
      file: common-services.yml
      service: lb-ui
    links:
      - zendserver

  zendserver:
    extends:
      file: common-services.yml
      service: zendserver
    image: janatzend/zend-server:-php7.2-apache
    environment:
      - APACHE_ULIMIT_MAX_FILES="ulimit -n 4096"
    links:
      - 'mysql:DB'

  mysql:
    extends:
      file: common-services.yml
      service: mysql
