lb:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
    - "8888:80"
    
zendserver:
  image: sb/zs:9.0
  links:
    - 'mysql:DB'
  environment:
    CLUSTER: 'true'
    VIRTUAL_HOST: localhost
    APACHE_ULIMIT_MAX_FILES: ulimit -n 4096
  volumes:
    - .:/share 

mysql:
  image: 'tutum/mysql:5.5'
  ports:
    - '3306'
  environment:
    MYSQL_PASS: 'admin'
    NAME: 'ZendServer'
        
