version: "2"

services:

  lb:
    extends:
      file: common-services.yml
      service: lb
    links:
      - zendserver

  zendserver:
    extends:
      file: common-services.yml
      service: zendserver
    build:
      context: .
      dockerfile: Dockerfile.apache.dev
    links:
      - 'mysql:DB'
    environment:
      - APACHE_ULIMIT_MAX_FILES="ulimit -n 4096"

  mysql:
    extends:
      file: common-services.yml
      service: mysql
