version: "2"

services:

  lb:
    extends:
      file: common-services.yml
      service: lb

  zendserver:
    extends:
      file: common-services.yml
      service: zendserver
    image: janatzend/zend-server:9.1EA-php7.1-apache
    environment:
      - APACHE_ULIMIT_MAX_FILES="ulimit -n 4096"
      - TCP_PORTS=80, 10081
      - BALANCE=source
      - EXCLUDE_PORTS=443,10082

  mysql:
    extends:
      file: common-services.yml
      service: mysql
